import type { NextPage } from "next";
import Head from "next/head";
import { useRef } from "react";
import About from "../components/About";
import Background from "../components/Background";
import Contact from "../components/Contact";
import Hello from "../components/Hello";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Personal Website V4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="rgb(0, 0, 0)" />
      </Head>
      <Background />
      <div className="w-screen">
        <div
          className="pt-20 w-full h-[60vh] md:h-screen px-8 sm:px-6 md:px-0"
          id="hello"
        >
          <Hello />
        </div>
        <div
          className="w-full h-[80vh] md:h-screen px-8 sm:px-6 md:px-0"
          id="about"
        >
          <About />
        </div>
        <div
          className="pb-20 w-full h-[100vh] md:h-screen px-8 sm:px-6 md:px-0"
          id="contact"
        >
          <Contact />
        </div>
      </div>
      <Navbar />
    </>
  );
};

export default Home;
