import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Hello from "../components/Hello";
import Navbar from "../components/Navbar";
import Project from "../components/Project";

const Home: NextPage = () => {
  return (
    <main className="w-full h-full">
      <Head>
        <title>Personal Website V4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row w-full">
        <div className="flex flex-col w-1/2 bg-zinc-900 items-end">
          <Hello />
          <Project />
          <About />
          <Contact />
        </div>

        <div className="flex flex-col w-1/2 bg-zinc-900 fixed right-0 top-0 bottom-0">
          <Navbar />
        </div>
      </div>
    </main>
  );
};

export default Home;
