import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import About from "../components/About";
import Background from "../components/Background";
import Contact from "../components/Contact";
import Hello from "../components/Hello";
import Navbar from "../components/Navbar";
import Project from "../components/Project";

const Home: NextPage = () => {
  const [pageHeight, setPageHeight] = useState(0);
  // const [scrollPosition, setScrollPosition] = useState(0);

  const refs: any = {
    hello: useRef(null),
    projects: useRef(null),
    about: useRef(null),
    contact: useRef(null),
  };

  // const handleScroll = () => {
  //   const viewport = document.getElementById("viewport");
  //   const position = viewport!.scrollTop;
  //   setScrollPosition(position);
  // };

  const handleSelect = (e: any) => {
    e.preventDefault();
    let elemId = e.target.id;
    refs[elemId].current.scrollIntoView({ behavior: "smooth" });
  };

  // useEffect(() => {
  //   const viewport = document.getElementById("viewport");
  //   const scroll = document.getElementById("scroll");
  //   // alert(viewport?.clientHeight);
  //   setPageHeight(viewport!.clientHeight);
  //   scroll?.addEventListener("scroll", (event) => {
  //     setScrollPosition(scroll.scrollTop);
  //     console.log(scroll.scrollTop);
  //     // alert(scroll?.scrollTop);
  //   });

  //   return () => {
  //     window.removeEventListener("scroll", handleScroll);
  //   };
  // }, []);

  return (
    <main className="w-full top-0 bottom-0 bg-black/50 snap-y snap-mandatory">
      <Head>
        <title>Personal Website V4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background />

      <Hello ref={refs.hello} id="hello" />
      <Project ref={refs.projects} id="projects" />
      <About ref={refs.about} id="about" />
      <Contact ref={refs.contact} id="contact" />

      <Navbar />
    </main>
  );
};

export default Home;
